project_name: cryptctl
release:
  github:
    owner: opensecrecy
    name: cryptctl
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X "github.com/opensecrecy/cryptctl/commands.Version={{.Env.VERSION}}"

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
brews:
  - name: cryptctl
    repository:
      owner: opensecrecy
      name: homebrew-cryptctl
    commit_author:
      name: shubhindia
      email: shubhindia123@gmail.com
    folder: Formula
    homepage: "https://github.com/opensecrecy/cryptctl"
    description: "CLI for managing secrets to be used with encrypted-secrets"