name: CI
on:
  push:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 5m
          skip-cache: true

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: build
        run: |
          make ARCH=arm64 build_macos
          make ARCH=amd64 build_macos
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/tcnksm/ghr@latest
          ghr -c ${{ github.sha }} ${{ github.ref_name }} bin/